identity/identity.go
identity/identity_suite_test.go

Needed to add a key for "identity" since the rest of the identity is
wrapped in another dict under that
`{"identity": {"account_number": "0000001"}}`

Set the correct JSON for the identity

---

logging/cloudwatch/hook.go

We lose logs on patchman-engine, which is using this library, because we exit process before all logs are exported to cloudwatch. In order to solve this, we need to be able to manually flush the accumulated messages in a blocking manner.

Add Flush method for manually sending exporting accumulated logs

---

logging/cloudwatch/hook.go

It's possible for the sequence tokens to get out of whack if multiple
process write to the log stream. We avoided this by having each pod
write to it's own log stream, but this still comes up on occassion.
This fix will retry the batch if we encounter the invalid token error
and reset the sequence token to the expected sequence token.
RHCLOUD-12772
Signed-off-by: Stephen Adams <tsadams@gmail.com>

[fix] catch and retry batches if we get a bad token

---

identity/identity.go
identity/identity_suite_test.go

We needed this code in our application and I thought it'd be a good addition to the middleware.
I'd like to add a test, but I only found one test suite that seems a lot more focused on testing the requests. I can add a new test suite if that's the case - should it go in the same file (identity_suite_test.go) or a different file?

Add GetIdentityHeader function

---

identity/identity.go
identity/identity_suite_test.go

Our gateways are moving the org_id field to the top level of the identity header. This commit adapts the identity middleware to that change.
See https://issues.redhat.com/browse/RHCLOUD-17653 for details.

add support for top level org_id field

---

identity/identity.go
identity/identity_suite_test.go

If the top-level org_id is missing (old client) populate it from the internal one.
This behavior was requested in the identity lib (github.com/RedHatInsights/identity). Backporting here for consistency.

top-level org_id fallback

---

identity/identity.go
identity/identity_suite_test.go

`auth_time` comes from the gateway as an int, not a string

Fix auth time type, add more thorough test header

---

identity/identity.go
identity/identity_suite_test.go

Update identity-header check to check for non-strict / missing account numbers.

Update identity check to allow missing account-numbers

---

identity/identity.go

This will help us figure out what goes wrong when a system is missing
values in their identity header

[log] Add logging for identity header

---

identity/identity.go

The AuthTime is a float32, not an int

[fix] AuthTime bug

---

identity/identity.go
identity/identity_suite_test.go

Tests that use X509 certificates come from turnpike which does not
include org_id or account numbers. We need to account for that

[task] Allow X509 requests without an account

---

identity/identity.go
identity/identity_suite_test.go

We should only fail the org_id check when the id is missing completely.
If we have it in the top level, but not in `internal` that should be
okay.

Fix org_id check

---

identity/identity.go

When this change went in, it requires auth_type. It's possible for us to
get some uploads that do not have this field. Mainly some CCX failed
payloads

[task] make auth_type optional

---

README.md
logging/cloudwatch/batch_writer.go
logging/cloudwatch/hook.go

Separate the CloudWatch Logs batch-writing client from the logrus
Hook data structure. This allows other logging frameworks to use
the BatchWriter client, and logrus clients can use both the
BatchWriter and the Hook.
```go
w, err := cloudwatch.NewBatchWriter(groupName, streamName, awsCfg)
hook := cloudwatch.NewLogrusHook(w)
logrus.Hooks.Add(hook)
```
Other logging frameworks can still make use of the CloudWatch logs API client (`BatchWriter`) and don't need to use the logrus hook:
```go
w, err := cloudwatch.NewBatchWriter(groupName, streamName, awsCfg)
zerolog.Out(io.MultiWriter(os.Stderr, w))
```

refactor: add BatchWriter

---

identity/identity.go
identity/identity_suite_test.go

Supports identity type `ServiceAccount` which will have a `service_account` object consisting of `username` and `client_id`. Other top-level fields not specific to the identity type will remain the same as `User` and `System`.
Related PR constructing the `x-rh-identity` for service accounts: https://github.com/RedHatInsights/insights-3scale/pull/297

Add support for service account identities

---

identity/identity.go

Guys, I am testing v2 against our app and it turns out RBAC service is unable to parse this:
```
{
"identity": {
"account_number": "0369233",
"org_id": "3340851",
"internal": {
"org_id": "3340851",
"auth_time": 6300
},
"user": {
"username": "jdoe",
"email": "jdoe@acme.com",
"first_name": "John",
"last_name": "Doe",
"is_active": true,
"is_org_admin": true,
"is_internal": false,
"locale": "en_US",
"user_id": ""
},
"system": {},
"associate": {
"Role": null,
"email": "",
"givenName": "",
"rhatUUID": "",
"surname": ""
},
"x509": {
"subject_dn": "",
"issuer_dn": ""
},
"service_account": {
"client_id": "",
"username": ""
},
"type": "User",
"auth_type": "basic-auth"
},
"entitlements": {
"cost_management": {
"is_entitled": true,
"is_trial": false
},
"hybrid_cloud": {
"is_entitled": true, …
```

Make service account ommitable

---

go.mod
go.sum

Address mitigation for CVE-2024-45338

chore(deps): bump golang.org/x/net to 0.33.0

---

.github/workflows/weekly-bump.yaml

This adds a weekly gobump job, it is a utility I wrote that bumps dependencies while keeping Go version untouched in `go.mod`. In order for this to work, we need to set GHA token permissions to file PRs from GHA. After this is merged, every Sunday afternoon gobump will run and if there is a dep that can be updated a PR will be filed.
https://github.com/lzap/gobump

chore: add gobump weekly

---

identity/identity.go
identity/identity_suite_test.go

The `user_id` filed is required per the identity schema [1], which this adds to the `ServiceAccount` struct.
[1] https://github.com/RedHatInsights/identity-schemas/blob/main/3scale/schema.json#L145

Add missing `user_id` field to ServiceAccount identity

---

.github/workflows/tests.yaml
go.mod
go.sum

SSIA
Used a tool to update all dependencies up to the version that is supporeted by Go 1.21:
https://github.com/lzap/gobump
Everything was updated except gomega library, that one needs more modern Go.
Although Go Toolbox already contains 1.22 I think we should keep the minimum version as low as possible.

Update to Go 1.21
